In [1]:
# We import numpy with its abbreviation "np"
import numpy as np

# We can create one-dimensional arrays with the function np.array()
array_onedim = np.array([1,2,3,4,5])

# Two-dimensional array
array_bidim = np.array([[1,2,3],
                       [4,5,6]])

# Three-dimensional array
array_tridim = np.array([[[1,2,3],
                         [4,5,6]],
                        [[7,8,9],
                        [10,11,12]]])

In [3]:
# One-dimensional array attributes
array_onedim.shape, array_onedim.ndim, array_onedim.dtype, array_onedim.size, type(array_onedim)

((5,), 1, dtype('int32'), 5, numpy.ndarray)

In [4]:
# Two-dimensional array attributes
array_bidim.shape, array_bidim.ndim, array_bidim.dtype, array_bidim.size, type(array_bidim)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [5]:
# Three-dimensional array attributes
array_tridim.shape, array_tridim.ndim, array_tridim.dtype, array_tridim.size, type(array_tridim)

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

In [6]:
# We import pandas as pd, and we create a DataFrame from the two-dimensional array
import pandas as pd

data = pd.DataFrame(array_bidim)
data

0  1  2
0  1  2  3
1  4  5  6

In [7]:
# We create an array of size 4x3, formed only by ones (1)
ones = np.ones((4,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# We create an array of size 2x4x3, formed only by zeros (0)
zero = np.zeros((2,4,3))
zero


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# We create an array of numbers in the range from 0 to 100, with a step of 5
array_1 = np.arange(0, 100, 5)
array_1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [10]:
# We create an array of random integer numbers between 0 and 10, of size (2,5)
array_2 = np.random.randint(0, 10, (2,5))
array_2


array([[9, 4, 1, 7, 4],
       [7, 0, 8, 4, 8]])

In [12]:
# We create an array of decimal random numbers between 0 and 1, of size (3,5)
array_3 = np.random.random((3,5))
array_3

array([[0.03657402, 0.11342831, 0.01378612, 0.52884681, 0.91074438],
       [0.78132111, 0.43526136, 0.82647198, 0.45573254, 0.94112344],
       [0.07428089, 0.064696  , 0.87003479, 0.6437407 , 0.74721016]])

In [13]:
# We set the "seed" of random numbers to 27
np.random.seed(27)

# We create an array of random integer numbers between 0 and 10, of size (3,5)
array_4 = np.random.randint(0, 10, (3,5))
array_4

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

In [14]:
# Find the unique values of the array_4
np.unique(array_4)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [15]:
# We extract the element of the index 1 of the array_4
array_4[1]

array([5, 8, 9, 1, 2])

In [16]:
# We extract the first two rows of the array_4
array_4[:2]

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [17]:
# We extract the first two data from the first two rows of the array_4
array_4[:2, :2]

array([[3, 8],
       [5, 8]])

In [18]:
# We create two arrays of size 3x4: one filled with random numbers between 0 and 10, and another filling of ones.
array_5 = np.random.randint(0, 10, (3, 4))
array_6 = np.ones((3,4))

In [19]:
# We invoke the array_5
array_5

array([[3, 0, 5, 3],
       [3, 6, 7, 2],
       [7, 8, 5, 7]])

In [20]:
# We invoke the array_6
array_6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
# We add the two array
array_5 + array_6

array([[4., 1., 6., 4.],
       [4., 7., 8., 3.],
       [8., 9., 6., 8.]])

In [22]:
# We now create an array of size (4,3) filled with ones
array_7 = np.ones((4,3))
array_7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# We will try to add the array 6 and 7
array_6 + array_7

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [24]:
# What is the reason for the above error? What should we take into account so that it does not happen?
# That our arrays have to have the same size


# Then we will create another array of size (4,3) full of ones
array_8 = np.ones((4,3))
array_8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
# We subtract the array_8 from array_7
array_8 - array_7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# We create another two arrays of size 3 x 3 with random numbers from 1 to 5
array_9 = np.random.randint(1, 5, (3, 3))
array_10 = np.random.randint(1, 5, (3, 3))

In [27]:
# We invoke the array_9
array_9

array([[2, 3, 4],
       [1, 4, 4],
       [2, 3, 4]])

In [28]:
# We invoke the array_10
array_10

array([[2, 1, 4],
       [4, 1, 2],
       [2, 4, 1]])

In [29]:
# Multiply the last two arrays together
array_9 * array_10

array([[ 4,  3, 16],
       [ 4,  4,  8],
       [ 4, 12,  4]])

In [30]:
# We raise the array_9 to the square
array_9**2

array([[ 4,  9, 16],
       [ 1, 16, 16],
       [ 4,  9, 16]], dtype=int32)

In [31]:
# Find the square root of the array_10
np.sqrt(array_10)

array([[1.41421356, 1.        , 2.        ],
       [2.        , 1.        , 1.41421356],
       [1.41421356, 2.        , 1.        ]])

In [32]:
# Find the average of the values in the array_9
array_9.mean()

3.0

In [33]:
# Find the maximum value of the values of the array_9
array_9.max()

4

In [34]:
# Find the minimum value of the values of the array_9
array_9.min()


1

In [35]:
# We change the shape of the array_9 for one of 9x1, and we store it as array_11
array_11 = array_9.reshape((9,1))

In [36]:
# We invoke the array_11
array_11


array([[2],
       [3],
       [4],
       [1],
       [4],
       [4],
       [2],
       [3],
       [4]])

In [37]:
# We transpose the array_11
array_11.T

array([[2, 3, 4, 1, 4, 4, 2, 3, 4]])

In [38]:
# We compare the array_9 and the array_10, to know which elements of the array_9 are greater than those of the array_10
array_12 = array_9 > array_10
array_12


array([[False,  True, False],
       [False,  True,  True],
       [False, False,  True]])

In [39]:
# What types of data are part of the result array?


# Let's see your new data types
array_12.dtype


dtype('bool')

In [40]:
# Any of the elements of the array_9 is equal to its equivalent in the array_10?
array_9 == array_10 

array([[ True, False,  True],
       [False, False, False],
       [ True, False, False]])

In [41]:
# We compare both arrays again, on this occasion with >=
array_9 >= array_10 

array([[ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [42]:
# We look for the elements of the array_9 that are greater than 2
array_9 > 2

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True]])

In [43]:
# Sort the elements in the array_9 from smallest to largest
np.sort(array_9)

array([[2, 3, 4],
       [1, 4, 4],
       [2, 3, 4]])